### ISSUE TITLE
Issue with Google oAuth and container version 5.120.2

### ISSUE THREAD

**Issue by killroy1971** [ronivay/xen-orchestra-docker#26]
The previous container, version 5.119.0 handles Google oAuth fine. When I upgraded to version 5.120.0, I now get this error message: Cannot read properties of undefined (reading 'id').

Now I can downgrade to 5.119.0, but I'd like to know what the above error message means. I double checked the Google Authentication module's settings and everything was set as it should be. 

Any ideas?

**Comment by ronivay** [comment]
Hi,

There have been some recent changes to google-auth and some auth stuff in general according to commits. eq version update: https://github.com/vatesfr/xen-orchestra/commit/9c9c11104b540d6d5fda46914e3c2544448cecaa

I doubt this container build has anything to do with the plugin not working properly. I'd suggest trying to build container manually so that you're in latest XO master branch commit and see if it makes any difference. If not, best place to start would be xcp-ng forum as I'm not a maintainer of actual application code.

**Comment by killroy1971** [comment]
I'll take a look see.  Thank you.
