### ISSUE TITLE
Request: Latest-official tag

### ISSUE THREAD

**Issue by nuentes** [ronivay/xen-orchestra-docker#4]
I noticed that with the tags, there are 2 choices:

1) latest: uses the nightlies
2) specific version

Would it be possible to create a new tag of "latest-official" (or something else) that doesn't use the nightlies, but would upgrade official incremental releases (i.e. 5.47 to 5.48 when officially released).

**Comment by ronivay** [comment]
Hi,

Official XOA versioning was never same with from sources built xo-server/xo-web combination. They are two different things.

Actually the tagging scheme described in this container readme is already outdated since xen orchestra doesn’t do tagged release anymore on their github. As you might see from container tags, the most recent non-latest is very old for this reason. I should update readme.

There really isn’t a way to automate this behaviour unfortunately.
