### ISSUE TITLE
maxTokenValidity in xo-server's config

### ISSUE THREAD

**Issue by Miky028** [ronivay/xen-orchestra-docker#42]
Is it possible to increase maxTokenValidity settings?
Related conversation is [here](https://xcp-ng.org/forum/topic/6809/xoa-token-expire-date-how-can-i-set-it-to-an-later-date).

I believe that current setting is ..
`maxTokenValidity = '0.5 year'`

THX for super docker image.

**Comment by ronivay** [comment]
Instead of adding support for all these custom config options, i just merged a support for preserving the config file on volume or bind mount and the initial config is only generated once when container starts if missing. This way you can add whatever config modification there that you want and it'll be preserved. Check the updated README configuration section. Updated container image will be available shortly in dockerhub.
